### ISSUE TITLE
Bash Error 

### ISSUE THREAD

**Issue by droid-Q** [Microsoft/CommandLine-Documentation#16]
After installing bash.On the powershell  i tried to run bash.But it shows error:"Error: 0x80070057".

**Comment by raeesiqbal** [comment]
Maybe related to https://github.com/Microsoft/BashOnWindows/issues/2

**Comment by richardjharding** [comment]
I have the same issue - when I login as the built in administrator account and run the install for that profile it works fine

I have experimented with changing the codepage in cmd to 65001 as suggested in the link above but it still errors, have also tried lxrun /uninstall  and re-install but get the same error

Error seen in both powershell (normal and elevated) and in cmd

**Comment by droid-Q** [comment]
@richardjharding ,I have fixed the problem.You can try to uncheck the option that using old console.
<img width="455" alt="2016-04-08 8 28 30" src="https://cloud.githubusercontent.com/assets/708277/14383633/f30fdb00-fdc8-11e5-9bd0-397e3fefe91a.png">

**Comment by richardjharding** [comment]
awesome  thanks! - I could have sworn I tried that yesterday but today it works thanks

**Comment by bitcrazed** [comment]
This is known internally as the Legacy Console Issue :)

Thanks for reporting.
