### ISSUE TITLE
it doesn't work on my turing machine

### ISSUE THREAD

**Issue by Lemmmy** [Microsoft/CommandLine-Documentation#2]
here is my machine configuration

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/State_diagram_3_state_busy_beaver_4.JPG/500px-State_diagram_3_state_busy_beaver_4.JPG)

**Comment by BTCTaras** [comment]
I think you need to update your hardware

**Comment by five23** [comment]
Have you flashed your BIOS?

**Comment by Lemmmy** [comment]
yeah, it screamed it was being violated and then called the police

never flashing again

**Comment by BTCTaras** [comment]
Computer BIOS, not the musician Bios

**Comment by Lemmmy** [comment]
i'm not into that genre

**Comment by espectalll123** [comment]
Have you tried turning it off and on again?

**Comment by Lemmmy** [comment]
yes

**Comment by camsteffen** [comment]
did you try Ctrl+Alt+Delete?

**Comment by bitcrazed** [comment]
LOL :) Closing as "too funny" :)
