### ISSUE TITLE
nginx cannot start worker process

### ISSUE THREAD

**Issue by hjc4869** [Microsoft/CommandLine-Documentation#21]
`apt-get install nginx` , edit `/etc/nginx/sites-enabled/default` to disable ipv6 (which causes another error) and use command `nginx` to start the server, the server failed to start the worker process.
here is my `/var/log/nginx/error.log`
```
2016/04/07 11:48:21 [alert] 420#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/07 11:48:21 [alert] 420#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/07 11:48:21 [alert] 420#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/07 11:48:21 [alert] 420#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
```

**Comment by cowens** [comment]
Looking through the strace for nginx, it looks like the bad syscall is either:

```futex(0x7ff5fffef6a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7ff5ffe00740) = -1 EAGAIN (Resource temporarily unavailable)```

or

```bind(6, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EINVAL (Invalid argument)```
