### ISSUE TITLE
sudo su - and sudo -i throw an odd error

### ISSUE THREAD

**Issue by cowens** [Microsoft/CommandLine-Documentation#25]
I added a new user with `adduser`, added the user to `/etc/sudoers` with `visudo`, logged in as the user with `su - user`, then attempt to become root with `sudo su -` and `sudo -i`.  Both throw the following error (but appear to log me in as root):

```mesg: /dev/tty: Operation not permitted```

**Comment by bitcrazed** [comment]
Thanks for reporting. 

Sudo and user accounts aren't fully functional in the first preview. We're working on many improvements to user accounts and sudo support for a future build.

Bear with us :wink:
