### ISSUE TITLE
npm install failing. Symlink problems?

### ISSUE THREAD

**Issue by Sparticuz** [Microsoft/CommandLine-Documentation#26]
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! path ../mime/cli.js
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall symlink

npm ERR! Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/mnt/c/users/kyle/Documents/dev/listomaniapi/node_modules/.bin/mime'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/mnt/c/users/kyle/Documents/dev/listomaniapi/node_modules/.bin/mime']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../mime/cli.js',
npm ERR!   dest: '/mnt/c/users/kyle/Documents/dev/listomaniapi/node_modules/.bin/mime',
npm ERR!   parent: 'listomaniapi' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/users/kyle/Documents/dev/listomaniapi/npm-debug.log
npm ERR! code 1
root@localhost:~/dev/listomaniapi#

**Comment by cowens** [comment]
How did you try to install npm?

**Comment by Sparticuz** [comment]
`curl -sL https://deb.nodesource.com/setup_4.x | bash -`
`apt-get install nodejs`

It's what is on nodejs.org's site

**Comment by filipeaguiar** [comment]
I've got a similar error when trying to install node and npm using [nvm](https://github.com/creationix/nvm)

**Comment by ThaJay** [comment]
same thing here.
A subdependency would love to make a symlink, and `npm i` fails because it can't.
We do have symlinks in `cmd` through `mklnk /J` so I don't really get why it's not possible in WSL yet.

```npm WARN package.json babel-plugin-transform-regenerator@6.3.26 No repository field.
npm WARN package.json babel-regenerator-runtime@6.5.0 No repository field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json fbjs-scripts@0.4.0 No repository field.
npm ERR! Error: EPERM, symlink '../JSONStream/index.js'
npm ERR!  { [Error: EPERM, symlink '../JSONStream/index.js'] errno: 50, code: 'EPERM', path: '../JSONStream/index.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.4.0+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /mnt/c/dev/scan-app
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../JSONStream/index.js
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, symlink '../JSONStream/index.js'```

**Comment by nerdofsteel** [comment]
Using this I've had some luck installing some npm modules, but it still does with permission errors whenever npm tries to rename a file.

INSTALL GLOBAL NPM PACKAGES
npm config set unsafe-perm true

BYPASS SYMLINK ISSUES
npm install --no-bin-links

**Comment by Sparticuz** [comment]
> We have symlinks in cmd through mklink /J so I don't really get why it's not possible through WSL yet.

What's odd is the `ln -s` seems to work fine

**Comment by sergio-garcia** [comment]
In my tests, using pip, I was unable to create a virtualenv in my user folder.
What I saw is that we are unable to create a symlink from ubuntu filesystem to /mnt/c/ (the windows filesystem).

**Comment by Sparticuz** [comment]
I think you've got the ln -s backwards, mine created just fine inside bash
`lrwxrwxrwx 1 root root   31 Apr  7 01:24 dev -> /mnt/c/users/kyle/Documents/dev/`

**Comment by ThaJay** [comment]
I was unable to use `ln -s` on `/mnt/c/` but it did work for me in the unix filesystem, for instance at `~/`.
a symlink created through `mklink /J` in cmd showed up in my bash, but it did look a bit strange:
```
$ l
ls: cannot access core: Input/output error
total 8.0K
d????????? ? ?    ?       ?            ? core/
-rwxrwxrwx 1 root root 1.2K Apr  7 15:54 index.js*
-rwxrwxrwx 1 root root  164 Apr  7 15:54 react.js*
drwxrwxrwx 2 root root    0 Mar 31 16:14 subcomponents/
drwxrwxrwx 2 root root    0 Mar 31 16:14 viewcomponents/
```

**Comment by sergio-garcia** [comment]
I think the problem for both virtualenv and npm is that those tools tries to create links to the Lxss filesystem.
```
root@localhost:/mnt/c/Users/sergi# ln -s /root .
ln: failed to create symbolic link ‘./root’: Operation not permitted
```

**Comment by filipeaguiar** [comment]
It appears to be a problem with *tar*. It doesn't create symlinks ever. Every tool that I've tried to install that uses tar with symlinks fails.

**Comment by Sparticuz** [comment]
More info here: https://github.com/Microsoft/BashOnWindows/issues/3

**Comment by allenleein** [comment]
Just `sudo npm install -g npm@5.3.0`

**Comment by aswathykrishna18** [comment]
$ npm install -g npm
C:\Users\aswathy\AppData\Roaming\npm\npx -> C:\Users\aswathy\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
npm ERR! path C:\Users\aswathy\AppData\Roaming\npm\npm
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\aswathy\AppData\Roaming\npm\npm'
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Users\aswathy\AppData\Roaming\npm\npm'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, open 'C:\Users\aswathy\AppData\Roaming\npm\npm'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'open',
npm ERR!      path: 'C:\\Users\\aswathy\\AppData\\Roaming\\npm\\npm' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, open \'C:\\Users\\aswathy\\AppData\\Roaming\\npm\\npm\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\aswathy\\AppData\\Roaming\\npm\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aswathy\AppData\Roaming\npm-cache\_logs\2018-01-16T10_46_38_513Z-debug.log

**Comment by recaic** [comment]
> 
> 
> Using this I've had some luck installing some npm modules, but it still does have issues with permission errors whenever npm tries to rename a file.
> 
> INSTALL GLOBAL NPM PACKAGES
> `npm config set unsafe-perm true`
> 
> CLEAN CACHE
> `npm cache clean`
> 
> BYPASS SYMLINK ISSUES
> `npm install --no-bin-links`

Thank. It's working:))

**Comment by aqeebimtiaz** [comment]
> Using this I've had some luck installing some npm modules, but it still does have issues with permission errors whenever npm tries to rename a file.
> 
> INSTALL GLOBAL NPM PACKAGES
> `npm config set unsafe-perm true`
> 
> CLEAN CACHE
> `npm cache clean`
> 
> BYPASS SYMLINK ISSUES
> `npm install --no-bin-links`

This worked like a charm! Thank you!

**Comment by razonklnbd** [comment]
In my case I mount vfat into media so my ubuntu can't create symlinks into that mount point and raise this kind of error.

**Comment by ShivanshSharma1** [comment]
Fix the code if the deploy log in Netlify gives any error or warning and it will deploy.

**Comment by CodeWithHiteshYT** [comment]
> Using this I've had some luck installing some npm modules, but it still does have issues with permission errors whenever npm tries to rename a file.
> 
> INSTALL GLOBAL NPM PACKAGES
> `npm config set unsafe-perm true`
> 
> CLEAN CACHE
> `npm cache clean`
> 
> BYPASS SYMLINK ISSUES
> `npm install --no-bin-links`

Thanks it worked...!!

**Comment by Dragonphy** [comment]
If you are using vs code, close it!

**Comment by killroy42** [comment]
I ran into symlink issues with weird relative paths:
` Error: EACCES: permission denied, symlink '../../../lib/node_modules/npm/man/man5/npm-shrinkwrap-json.5' -> '/usr/share/man/man5/npm-shrinkwrap-json.5'`

And now npm is borked, as the rollback failed...

**Comment by tetris-dev-web** [comment]
```
INSTALL GLOBAL NPM PACKAGES
npm config set unsafe-perm true

CLEAN CACHE
npm cache clean

BYPASS SYMLINK ISSUES
npm install --no-bin-links
```
It's working... perfect
