### ISSUE TITLE
Building a User Space

### ISSUE THREAD

**Issue by sferich888** [Microsoft/CommandLine-Documentation#3]
Instead of having an FAQ item like: https://github.com/Microsoft/CommandLine-Documentation/blob/live/commandline/WSL/faq.md#can-i-run-other-linux-distros-than-ubuntu

It would be good to show or explain how a fedora, arch, or other user space could be created. 

If the user space is truly separated from the WSL then you will only expand your testing by allowing other 'user spaces' to be created, and install applications ontop of them.

**Comment by bitcrazed** [comment]
We need to do a ton of engineering to make this capability happen. 

Right now, we need more testing of our supported scenarios in order to stabilize and solidify our existing infrastructure before we expand to support other scenarios.

**Comment by sferich888** [comment]
It looks like boot strap methods exsist: https://www.variantweb.net/blog/running-fedora-on-windows-10-using-wsl

**Comment by bitcrazed** [comment]
Getting something to just about run is one thing. Getting it to run smoothly, quickly, reliably, and safely is a whole different ballgame 😉
