### ISSUE TITLE
lxrun /uninstall /full doesn't remove all files

### ISSUE THREAD

**Issue by filipeaguiar** [Microsoft/CommandLine-Documentation#30]
I wanted to clean all modifications made on my wsl installation and ran a `lxrun /uninstall /full`. Then I ran `lxrun /install` to install it again.

The `/root/.bashrc` file has the same modifications that I've made before reinstalling `bash` and even some symlinks on a user that I created before where there after I created the user again.

I don't think that is the desired behavior for `lxrun /uninstall /full`.

**Comment by bluefire42** [comment]
Confirmed - I even had to remove the folder `%APPDATA%\local\lxss` before I ran `lxrun /install /y` again. Otherwise `lxrun /install /y` threw the Error 0x80070091 and did not finish the installation.

**Comment by bitcrazed** [comment]
Great feedback. Thanks for sharing.
