### ISSUE TITLE
Unable to install Java JDK or Runtime

### ISSUE THREAD

**Issue by temalo** [Microsoft/CommandLine-Documentation#31]
Using apt-get install default-jdk results in several failures related to dependencies:

Selecting previously unselected package libx11-doc.
Preparing to unpack .../libx11-doc_2%3a1.6.2-1ubuntu2_all.deb ...
Unpacking libx11-doc (2:1.6.2-1ubuntu2) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../libxt-dev_1%3a1.1.4-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.1.4-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up xorg-sgml-doctools (1:1.11-1) ...
Setting up x11proto-core-dev (7.0.26-1~ubuntu2) ...
Setting up libice-dev:amd64 (2:1.0.8-2) ...
Setting up libpthread-stubs0-dev:amd64 (0.3-4) ...
Setting up libsm-dev:amd64 (2:1.2.1-2) ...
Setting up libxau-dev:amd64 (1:1.0.8-1) ...
Setting up libxdmcp-dev:amd64 (1:1.1.1-1) ...
Setting up x11proto-input-dev (2.3-1) ...
Setting up x11proto-kb-dev (1.0.6-2) ...
Setting up xtrans-dev (1.3.5-1~ubuntu14.04.1) ...
Setting up libxcb1-dev:amd64 (1.10-2ubuntu1) ...
Setting up libx11-dev:amd64 (2:1.6.2-1ubuntu2) ...
Setting up libx11-doc (2:1.6.2-1ubuntu2) ...
Setting up libxt-dev:amd64 (1:1.1.4-1) ...
Setting up openjdk-7-jre-headless:amd64 (7u95-2.6.4-0ubuntu0.14.04.2) ...
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of default-jre-headless:
 default-jre-headless depends on openjdk-7-jre-headless (>= 7~u3-2.1.1); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.

dpkg: error processing package default-jre-headless (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
dpkg: dependency problems prevent configuration of openjdk-7-jre:amd64:
 openjdk-7-jre:amd64 depends on openjdk-7-jre-headless (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.

dpkg: error processing package openjdk-7-jre:amd64 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.dpkg: dependency problems prevent configuration of default-jre:
 default-jre depends on default-jre-headless (= 2:1.7-51); however:
  Package default-jre-headless is not configured yet.

dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached alreadydpkg: dependency problems prevent configuration of openjdk-7-jdk:amd64:
 openjdk-7-jdk:amd64 depends on openjdk-7-jre (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre:amd64 is not configured yet.

dpkg: error processing package openjdk-7-jdk:amd64 (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
dpkg: dependency problems prevent configuration of default-jdk:
 default-jdk depends on default-jre (= 2:1.7-51); however:
  Package default-jre is not configured yet.
 default-jdk depends on openjdk-7-jdk (>= 7~u3-2.1.1); however:
  Package openjdk-7-jdk:amd64 is not configured yet.

dpkg: error processing package default-jdk (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
dpkg: dependency problems prevent configuration of ca-certificates-java:
 ca-certificates-java depends on openjdk-7-jre-headless (>= 7~u3-2.1.1~pre1-1) | java6-runtime-headless; however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.
  Package java6-runtime-headless is not installed.
  Package default-jre-headless which provides java6-runtime-headless is not configured yet.
  Package openjdk-7-jre-headless:amd64 which provides java6-runtime-headless is not configured yet.

dpkg: error processing package ca-certificates-java (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 openjdk-7-jre-headless:amd64
 default-jre-headless
 openjdk-7-jre:amd64
 default-jre
 openjdk-7-jdk:amd64
 default-jdk
 ca-certificates-java
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by vivimice** [comment]
Successfully installed oracle jdk8 using a deb which was created on another amd64 pc using `java-package`

But failed to execute `java -version`, the program freezed and consumed an entrie core.

**Comment by tiger2wander** [comment]
Look like there are missing many low level API which JVM using.

**Comment by JasonMrX** [comment]
Hi,

I am having the exact same problem. Is this issue still open?
