### ISSUE TITLE
can't run win32 or win64 executables

### ISSUE THREAD

**Issue by kilobyte** [Microsoft/CommandLine-Documentation#32]
./test-win32.exe
bash: ./test-win32.exe: cannot execute binary file: Exec format error
/test-win64.exe
bash: ./test-win64.exe: cannot execute binary file: Exec format error

(These are just "hello world"s.)
The executables in question do work from cygwin, cmd or with wine-binfmt on real Linux.

**Comment by vivimice** [comment]
See: https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

> Third, note that Bash and Linux tools cannot interact with Windows applications and tools, and vice-versa. So you won’t be able to run Notepad from Bash, or run Ruby in Bash from PowerShell.

**Comment by tiger2wander** [comment]
Ubuntu inside Windows is real Linux, it run Linux binary, so it can not run Windows binary inside that box. This allow us to use existing mirror and repositories around the world without build from source for another binary format to run. The Linux kernel is deep integrated with Windows kernel, so it can get native performance level.

Cygwin has dll (Windows) libraries to wrap around POSIX api and allow applications inside it own environment to use, so .exe can run but not in deep level.

**Comment by kilobyte** [comment]
The decision how to run a binary on execve() is made 100% by the kernel not userland.  The kernel looks at the binary and then runs it as ELF or a.out, dispatches it to userland based on a hashbang or binfmt, etc.

On UoW the kernel is fully yours so it can do whatever you want -- including running it as a PE which just happen to be natively supported by that very same kernel.

**Comment by bitcrazed** [comment]
@kilobyte - appreciate your feedback. Rest assured, we're going to be looking into the interop story in the future, but we won't be adding this capability in the Windows 10 Anniversary Update timeframe.
