### ISSUE TITLE
execute bash error

### ISSUE THREAD

**Issue by Kotofay** [Microsoft/CommandLine-Documentation#37]
Microsoft Windows [Version 10.0.14316]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Alex>lxrun /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful! The environment will start momentarily...

C:\Users\Alex>bash -c "ls"
**Error: 0x80070057**

C:\Users\Alex>bash ~
**Error: 0x80070057**

**Comment by Kotofay** [comment]
Solved!
Clear mark by [ ] Use legacy console (requires relaunch).

**Comment by bitcrazed** [comment]
Legacy Console Issue
