### ISSUE TITLE
Access files via Windows Explorer

### ISSUE THREAD

**Issue by wasabigeek** [Microsoft/CommandLine-Documentation#38]
Hi - is it possible to access files in the root via Windows Explorer? Trying to open some files via Windows Programs like VSCode.

**Comment by jernejs** [comment]
It's possible but unsupported (and causes trouble if you actually do try it). The files are in %LOCALAPPDATA%\lxss

**Comment by trevren11** [comment]
Thank you @jernejs I had been looking everywhere to know where those files were.

**Comment by trevren11** [comment]
You can edit the files, just make sure to change the line endings.

**Comment by SonGokussj4** [comment]
@trevren11 Can you be more specific? So I can edit files being in /... and not /mount/c... but what is the problem here?

**Comment by trevren11** [comment]
@SonGokussj4 you should be able to edit files in both locations assuming you are referring to `root/` as `/` but several people have also had problems with editing outside of bash programs like vim and nano. I would only use the file explorer to view though if you can help it.
