### ISSUE TITLE
Cowsay failed

### ISSUE THREAD

**Issue by chadbrewbaker** [Microsoft/CommandLine-Documentation#40]
root@localhost:/mnt/c/Users/Giant_ice5/afl-2.10b# cowsay
Command 'cowsay' is available in '/usr/games/cowsay'
The command could not be located because '/usr/games' is not included in the PATH environment variable.
cowsay: command not found

Seems you need to add a /usr/games directory in the default path?

**Comment by cowens** [comment]
I don't believe it is in the PATH by default in normal Ubuntu either. You can add it in your  ~/.profile file by saying

    PATH="/usr/games:$PATH"
