### ISSUE TITLE
Support for ARM processors

### ISSUE THREAD

**Issue by v217** [Microsoft/CommandLine-Documentation#43]
Will there be support for ARM processors in the near future?
The documentation states that right now only AMD64 architecture is supported, will that change?

**Comment by bitcrazed** [comment]
We're not aiming to support ARM at this time - we're focusing on delivering a solid x64 version of Bash on Ubuntu on Windows. 

If you feel this is important to you, please be sure to write-up your scenario on our UserVoice page: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash
