### ISSUE TITLE
.sh script on /mnt/d

### ISSUE THREAD

**Issue by SonGokussj4** [Microsoft/CommandLine-Documentation#48]
From Windows I've created [New - Text Document] renamed [test.sh], opened in [Sublime Text 3]

Wrote:

```
while true; do
    echo $(date)
    sleep 5
done
```

Doesn't work. Writes some error that "expected do" on line with "done".

but when written:

`while true; do echo $(date); sleep 5; done`

Everything works.

**Comment by jessicah** [comment]
Are you sure you're using Unix newlines in your script? Sounds like it's possibly choking on a \r. If you add the typical #!/bin/bash to top of your script, you'll get the error: line 2: $'\r': command not found, whereas without the shebang, you'll just get the syntax error on the `done` line.

These are binaries straight from Ubuntu, so they typically will not support Windows newlines.

**Comment by SonGokussj4** [comment]
Thank you for your response. It was really that. Sublime set the new lines to [Windows]. I think.
Now whe set to [Unix], it works well in [ST3]
So thank you again :-)

How does the "unix place detachement" works?
When I create shell script and move it into:
`/mnt/c/Users/my_user/AppData/Local/lxss/root/ScriptFolder#`

- I can see it in Windows
- I can see it in bash when i go to:

 `cd /mnt/c/Users/my_user/AppData/Local/lxss/root/ScriptFolder/`
- I **can't** see it in bash when i go to `cd ~/ScriptFolder/`

**Comment by jessicah** [comment]
@SonGokussj4 if you moved/created the file from Win32, the Linux filesystem likely will have issues with the file. Manipulating files under %APPDATA%\lxss from Win32 is unsupported and will have bizarre side effects. You should copy files there using the Linux environment.
