### ISSUE TITLE
Cannot find "Windows Subsystem for Linux" in the "Turn Windows features on or off" menu

### ISSUE THREAD

**Issue by caleblloyd** [Microsoft/CommandLine-Documentation#5]
I followed the instructions at https://github.com/Microsoft/CommandLine-Documentation/blob/master/commandline/WSL/install_guide.md and cannot find"Windows Subsystem for Linux" in the "Turn Windows features on or off" menu.

I am running Windows 10 Home.  Does this require Pro?  Or does it require a certain build #?  I posted my build details in the graphics below:

![win-build](https://cloud.githubusercontent.com/assets/2414837/14323624/39774b68-fbef-11e5-9636-b4c0bd3fecf2.png)

**Comment by russalex** [comment]
Howdy, looks like you're not on build 14316 yet.  Make certain you're on the Windows Insider Fast ring and pick up today's build.

For the record, the first officially supported build was released today on the Insider Fast ring.  Official tweet is [here](https://twitter.com/GabeAul/status/717759462258249728).    Release notes are [here](http://aka.ms/wip14316). 

Also, important note.  This feature is for x64 builds only.  x86 is not supported and the option will not show.  Can't tell which version you have from the screenshot.

**Comment by caleblloyd** [comment]
Thanks, I'll wait for the preview build to come through in Windows Update.  I'm running x64.

**Comment by raeesiqbal** [comment]
@caleblloyd You can actually goto "Updates and Security" in Settings and click "Check for Updates" to see the latest build update.

**Comment by caleblloyd** [comment]
@raeesiqbal I just turned on Fast track, it's my understanding that it can take a couple days before the updates are available to me.  I'll keep checking Windows Update until it does!

**Comment by popstas** [comment]
Same, was slow level, just turned to fast, reboot and check for updates not brings update for me.

**Comment by raeesiqbal** [comment]
I'm not sure because it showed up for me right away.

**Comment by ThaJay** [comment]
<3
rebooting...

**Comment by popstas** [comment]
Today received build 14316!
