### ISSUE TITLE
running byobu it run route

### ISSUE THREAD

**Issue by thariman** [Microsoft/CommandLine-Documentation#57]
typing byobu    show:
Usage: route ..
...
...

typing byobu -v  show:
byobu version 5.74
tmux 1.8

running build 14332 using SP4.

Thank you

**Comment by bitcrazed** [comment]
Thanks for filing @thariman, but as per the readme, please could I ask you to re-file over on https://github.com/microsoft/bashonwindows? Aiming to wind-down this issue tracker soon.
