### ISSUE TITLE
Can Bash and Windows Subsystem for Linux be Open Sourced?

### ISSUE THREAD

**Issue by sirinath** [Microsoft/CommandLine-Documentation#6]
Since Linux is open source perhaps the shell and subsystem components can be open sourced?

**Comment by WilliamFeely** [comment]
I believe the bash.exe program in Windows 10 is simply a command-line wrapper to download and install the Ubuntu command-line distribution.  I bet it will stay closed-source subject to the Microsoft Software License Terms for Windows.
For Microsoft's sake, hope the subsystem components aren't made from Linux source code, or they will have to either open source them or cancel the whole project; Linux is under the terms of the GNU General Public License version 2.

**Comment by bitcrazed** [comment]
This is a frequent ask, but not something we have in the plans right now.

Right now, we're working hard to ensure this is a stable environment to help developers be as productive as they can on Windows and in Bash (on Windows).
