### ISSUE TITLE
`mount` gives Incorrect Results

### ISSUE THREAD

**Issue by zenware** [Microsoft/CommandLine-Documentation#67]
As per the documentation 
> You can also access your local machine’s filesystem from within the Linux Bash shell – you’ll find your local drives mounted under the /mnt folder. For example, your C: drive is mounted under /mnt/c:

in the [Live Command Line WSL FAQ](https://github.com/Microsoft/CommandLine-Documentation/blob/a117ac5b67ca4a520c3c65f6819f602b737f4a3f/commandline/WSL/faq.md)

I really can _access_ my C drive under the `/mnt` folder.
```
# ls -la /mnt
total 12
drwxr-xr-x 2 root root 0 Jan  1  1970 ./
drwxrwxr-x 2 root root 0 Jan  1  1970 ../
drwxrwxrwx 2 root root 0 May 27 00:43 c/
```
However, the C drive is not **mounted** under the `/mnt` folder, as per the output of the `mount` command.
```
# mount
rootfs on / type rootfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=404156k,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)
```
This is obviously not the right place to report this unless I'm just being pedantic about the documention. I'm hoping someone will refer me to the right location to list this as a bug in WSLs implementation of `mount` or the hypervisor that sits between the two filesystems. I want the documentation to be correct, currently it is not, due to a problem in the software.

**Comment by bitcrazed** [comment]
Many thanks for your thoughts on this.

While you're technically correct that your local drives aren't mounted as per the `mount` command, they're notionally mounted in that they don't *exist* under the `/mnt/` directory, they appear as if they're mounted under the `/mnt/` directory.

Also, please note: As per the [readme](https://github.com/Microsoft/CommandLine-Documentation/blob/live/README.md), please file new issues at our GitHub issues repro.

Thanks again.
