### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by Zolotkey** [Microsoft/CommandLine-Documentation#7]
1. Tmux does not start
2. If ssh'ed to a Linux Machine with a tmux session you can not press ctrl-a to reach any tmux commands
3. When creating a ssh key the console has issue rendering process.

**Comment by Magnificus36** [comment]
I also ran into 1 & 2 with screen.
"open fifo /var/run/screen/S-root/3214.tty.localhost: No such file or directory" when trying to start screen. And not being able to use Ctrl+a in the remote screen makes it kinda unworkable for me.

**Comment by bitcrazed** [comment]
TMux & screen are troublesome in this build. 

We've made some important improvements to our console to support some of these scenarios for future builds, but for now, you may want to steer clear of more advanced scenarios ;)

Rest assured though - we're working on fixing these kinds of issues.

**Comment by rothschilde** [comment]
screen is an "advanced scenario"?  ummm ok.
